### ISSUE TITLE
Informations à propos des API

### ISSUE THREAD

**Issue by bertrandmartel** [bouygues-telecom/bytel-api#1]
Bonjour, je me demandais qu'entendez vous par `requêter les serveurs d'API de Bouygues Télécom`.  Les API que vous utilisez sont les API de la Bbox ? ou de l'espace client ? 

D'après l'exemple : 
```
import { bytel } from 'bytel-api'

bytel.setup({ host: 'API-URL' })

bytel.api.register('authorization', req => {
  req.set('Authorization', 'MY-OAUTH-ACCESS-TOKEN')
})

bytel({ path: '/request/path' }).then(result => {
  // Do something fantastic with the results \o/
})
```
Il semble falloir renseigner une url et un access token. Peux etre utilisez vous des API fermés ?

Merci

Bertrand

**Comment by RasCarlito** [comment]
Bonjour Bertrand,

La lib a été conçu pour les API de l'espace client en mode "connecté".
Il faut donc avoir récupéré un token de la part des services OAuth de Bytel.

Si le projet vous intéresse on pourrait se croiser au technopôle pour en discuter :)

Bonne journée
